# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.16

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/steve/vscode/projects_comp410/googletest/build2/caesar-cipher-part-2-sc1513

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/steve/vscode/projects_comp410/googletest/build2/caesar-cipher-part-2-sc1513

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/steve/vscode/projects_comp410/googletest/build2/caesar-cipher-part-2-sc1513/CMakeFiles /home/steve/vscode/projects_comp410/googletest/build2/caesar-cipher-part-2-sc1513/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/steve/vscode/projects_comp410/googletest/build2/caesar-cipher-part-2-sc1513/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named GoogleTest

# Build rule for target.
GoogleTest: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 GoogleTest
.PHONY : GoogleTest

# fast build rule for target.
GoogleTest/fast:
	$(MAKE) -f CMakeFiles/GoogleTest.dir/build.make CMakeFiles/GoogleTest.dir/build
.PHONY : GoogleTest/fast

#=============================================================================
# Target rules for targets named ceaser.o

# Build rule for target.
ceaser.o: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 ceaser.o
.PHONY : ceaser.o

# fast build rule for target.
ceaser.o/fast:
	$(MAKE) -f CMakeFiles/ceaser.o.dir/build.make CMakeFiles/ceaser.o.dir/build
.PHONY : ceaser.o/fast

GoogleTest.o: GoogleTest.cc.o

.PHONY : GoogleTest.o

# target to build an object file
GoogleTest.cc.o:
	$(MAKE) -f CMakeFiles/GoogleTest.dir/build.make CMakeFiles/GoogleTest.dir/GoogleTest.cc.o
.PHONY : GoogleTest.cc.o

GoogleTest.i: GoogleTest.cc.i

.PHONY : GoogleTest.i

# target to preprocess a source file
GoogleTest.cc.i:
	$(MAKE) -f CMakeFiles/GoogleTest.dir/build.make CMakeFiles/GoogleTest.dir/GoogleTest.cc.i
.PHONY : GoogleTest.cc.i

GoogleTest.s: GoogleTest.cc.s

.PHONY : GoogleTest.s

# target to generate assembly for a file
GoogleTest.cc.s:
	$(MAKE) -f CMakeFiles/GoogleTest.dir/build.make CMakeFiles/GoogleTest.dir/GoogleTest.cc.s
.PHONY : GoogleTest.cc.s

decrypt.o: decrypt.c.o

.PHONY : decrypt.o

# target to build an object file
decrypt.c.o:
	$(MAKE) -f CMakeFiles/ceaser.o.dir/build.make CMakeFiles/ceaser.o.dir/decrypt.c.o
.PHONY : decrypt.c.o

decrypt.i: decrypt.c.i

.PHONY : decrypt.i

# target to preprocess a source file
decrypt.c.i:
	$(MAKE) -f CMakeFiles/ceaser.o.dir/build.make CMakeFiles/ceaser.o.dir/decrypt.c.i
.PHONY : decrypt.c.i

decrypt.s: decrypt.c.s

.PHONY : decrypt.s

# target to generate assembly for a file
decrypt.c.s:
	$(MAKE) -f CMakeFiles/ceaser.o.dir/build.make CMakeFiles/ceaser.o.dir/decrypt.c.s
.PHONY : decrypt.c.s

dictionary_hashtable.o: dictionary_hashtable.c.o

.PHONY : dictionary_hashtable.o

# target to build an object file
dictionary_hashtable.c.o:
	$(MAKE) -f CMakeFiles/GoogleTest.dir/build.make CMakeFiles/GoogleTest.dir/dictionary_hashtable.c.o
	$(MAKE) -f CMakeFiles/ceaser.o.dir/build.make CMakeFiles/ceaser.o.dir/dictionary_hashtable.c.o
.PHONY : dictionary_hashtable.c.o

dictionary_hashtable.i: dictionary_hashtable.c.i

.PHONY : dictionary_hashtable.i

# target to preprocess a source file
dictionary_hashtable.c.i:
	$(MAKE) -f CMakeFiles/GoogleTest.dir/build.make CMakeFiles/GoogleTest.dir/dictionary_hashtable.c.i
	$(MAKE) -f CMakeFiles/ceaser.o.dir/build.make CMakeFiles/ceaser.o.dir/dictionary_hashtable.c.i
.PHONY : dictionary_hashtable.c.i

dictionary_hashtable.s: dictionary_hashtable.c.s

.PHONY : dictionary_hashtable.s

# target to generate assembly for a file
dictionary_hashtable.c.s:
	$(MAKE) -f CMakeFiles/GoogleTest.dir/build.make CMakeFiles/GoogleTest.dir/dictionary_hashtable.c.s
	$(MAKE) -f CMakeFiles/ceaser.o.dir/build.make CMakeFiles/ceaser.o.dir/dictionary_hashtable.c.s
.PHONY : dictionary_hashtable.c.s

file_handler.o: file_handler.c.o

.PHONY : file_handler.o

# target to build an object file
file_handler.c.o:
	$(MAKE) -f CMakeFiles/GoogleTest.dir/build.make CMakeFiles/GoogleTest.dir/file_handler.c.o
	$(MAKE) -f CMakeFiles/ceaser.o.dir/build.make CMakeFiles/ceaser.o.dir/file_handler.c.o
.PHONY : file_handler.c.o

file_handler.i: file_handler.c.i

.PHONY : file_handler.i

# target to preprocess a source file
file_handler.c.i:
	$(MAKE) -f CMakeFiles/GoogleTest.dir/build.make CMakeFiles/GoogleTest.dir/file_handler.c.i
	$(MAKE) -f CMakeFiles/ceaser.o.dir/build.make CMakeFiles/ceaser.o.dir/file_handler.c.i
.PHONY : file_handler.c.i

file_handler.s: file_handler.c.s

.PHONY : file_handler.s

# target to generate assembly for a file
file_handler.c.s:
	$(MAKE) -f CMakeFiles/GoogleTest.dir/build.make CMakeFiles/GoogleTest.dir/file_handler.c.s
	$(MAKE) -f CMakeFiles/ceaser.o.dir/build.make CMakeFiles/ceaser.o.dir/file_handler.c.s
.PHONY : file_handler.c.s

shift_matrix.o: shift_matrix.c.o

.PHONY : shift_matrix.o

# target to build an object file
shift_matrix.c.o:
	$(MAKE) -f CMakeFiles/GoogleTest.dir/build.make CMakeFiles/GoogleTest.dir/shift_matrix.c.o
	$(MAKE) -f CMakeFiles/ceaser.o.dir/build.make CMakeFiles/ceaser.o.dir/shift_matrix.c.o
.PHONY : shift_matrix.c.o

shift_matrix.i: shift_matrix.c.i

.PHONY : shift_matrix.i

# target to preprocess a source file
shift_matrix.c.i:
	$(MAKE) -f CMakeFiles/GoogleTest.dir/build.make CMakeFiles/GoogleTest.dir/shift_matrix.c.i
	$(MAKE) -f CMakeFiles/ceaser.o.dir/build.make CMakeFiles/ceaser.o.dir/shift_matrix.c.i
.PHONY : shift_matrix.c.i

shift_matrix.s: shift_matrix.c.s

.PHONY : shift_matrix.s

# target to generate assembly for a file
shift_matrix.c.s:
	$(MAKE) -f CMakeFiles/GoogleTest.dir/build.make CMakeFiles/GoogleTest.dir/shift_matrix.c.s
	$(MAKE) -f CMakeFiles/ceaser.o.dir/build.make CMakeFiles/ceaser.o.dir/shift_matrix.c.s
.PHONY : shift_matrix.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... edit_cache"
	@echo "... GoogleTest"
	@echo "... ceaser.o"
	@echo "... GoogleTest.o"
	@echo "... GoogleTest.i"
	@echo "... GoogleTest.s"
	@echo "... decrypt.o"
	@echo "... decrypt.i"
	@echo "... decrypt.s"
	@echo "... dictionary_hashtable.o"
	@echo "... dictionary_hashtable.i"
	@echo "... dictionary_hashtable.s"
	@echo "... file_handler.o"
	@echo "... file_handler.i"
	@echo "... file_handler.s"
	@echo "... shift_matrix.o"
	@echo "... shift_matrix.i"
	@echo "... shift_matrix.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

